version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - ${APP_PORT}:3000
    volumes:
      - '.:/srv/app:rw'
    env_file:
      - .env
    networks:
      - go-backend

  mongodb:
    image: 'mongo:3.6.17'
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ./docker/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb-go-data:/data/db:rw
    ports:
      - ${MONGODB_PORT}:27017
    networks:
      - go-backend

volumes:
  mongodb-go-data: {}

networks:
  go-backend:
    driver: bridge